sudo: false
language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

# A local Mongo is required for tests
services: mongodb

# Thanks to: https://github.com/Masterminds/glide/issues/408#issuecomment-217493627
install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout v0.13.0 && go install && cd -
  - glide install
