checks_dir = "scripts"
event_end_time = "Tue Apr 19 22:58:12 EDT 2016"
intervals = "5s"
timeout = "4s"

[checks]
    [checks.1]
    check_name = "ping"
    filename = "check_ping"
    points = [ 1, 0, 0 ]
    args = "-w 200,50% -c 500,100% -t 5 -p 1 -H"

    [checks.2]
    check_name = "web"
    filename = "check_http"
    points = [ 10, 0, 0 ]
    args = "-t 5 -I"
