appname = "CNY Hackathon"

[server]
ip = "127.0.0.1"
http_port = "8080"
https_port = "8081"
cert = "certs/cert.pem"
key = "certs/key.pem"

[database]
mongodb_uri = "mongodb://127.0.0.1"
dbname = "scorengine"
